// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFEu_o5Mrq29wuSj7DUPNbMRGZc4EobM',
    appId: '1:906117445023:web:eb98be550e663f5755f9aa',
    messagingSenderId: '906117445023',
    projectId: 'astro-909a3',
    authDomain: 'astro-909a3.firebaseapp.com',
    storageBucket: 'astro-909a3.firebasestorage.app',
    measurementId: 'G-CC8JD1WCR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2D4dGupOB9ZF19CGZaODYIv2zLt-RQUI',
    appId: '1:906117445023:android:bc55a2b44861945f55f9aa',
    messagingSenderId: '906117445023',
    projectId: 'astro-909a3',
    storageBucket: 'astro-909a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXLMbrNac7bh0uvOQePIRI0u73BASd9v8',
    appId: '1:906117445023:ios:f14a590586f74c6155f9aa',
    messagingSenderId: '906117445023',
    projectId: 'astro-909a3',
    storageBucket: 'astro-909a3.firebasestorage.app',
    iosBundleId: 'com.example.astroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXLMbrNac7bh0uvOQePIRI0u73BASd9v8',
    appId: '1:906117445023:ios:f14a590586f74c6155f9aa',
    messagingSenderId: '906117445023',
    projectId: 'astro-909a3',
    storageBucket: 'astro-909a3.firebasestorage.app',
    iosBundleId: 'com.example.astroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFEu_o5Mrq29wuSj7DUPNbMRGZc4EobM',
    appId: '1:906117445023:web:e48eaa4fa1b0a2a855f9aa',
    messagingSenderId: '906117445023',
    projectId: 'astro-909a3',
    authDomain: 'astro-909a3.firebaseapp.com',
    storageBucket: 'astro-909a3.firebasestorage.app',
    measurementId: 'G-BDZG8S98KB',
  );
}
