name: astro_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  image: ^4.2.0
  intl: ^0.19.0
  http: ^0.13.5
  table_calendar: ^3.0.0 
  syncfusion_flutter_charts: ^20.2.40
  image_picker: ^0.8.7+4
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  firebase_core: ^3.8.0
  onesignal_flutter: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/zodiac_sign/
    - assets/images/Splash.png
    - assets/images/Profile.png
    - assets/images/Eclipse.png
    - assets/images/User.png
    - assets/images/VerificationCode.png
    - assets/images/PasswordReset.png
    - assets/images/Kundali.png

  # Fonts can be added here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
